# tomcat
server:
  port: 8002
spring:
  application:
    name: mango-backup
  boot:
    admin:
      client:
        url: "http://localhost:8000"
management:
  endpoints:
    web:
      exposure:
        include: "*"

# backup store
backup:
  datasource:
    host: localhost
    username: root
    password: 123
    database: mango